### ISSUE TITLE
Add clash check in blender during building (not only at export point)

### ISSUE THREAD

**Issue by joy13975** [joy13975/elfin-ui#12]
@parmef:
> Introduce clash check in blender during building (not only at export point) to avoid making proteins that run into each other.

From another bullet point:
> Add option to override clash checks (reworded).

**Comment by joy13975** [comment]
@parmef
I remember having this already implemented. Perhaps you ticked "Disable Auto Collision Check"?

![](https://i.gyazo.com/5c55f3017898e6c8fce17ad700a7e46d.gif)

**Comment by parmef** [comment]
You are correct, I had it disabled in the default start scene. problem solved.
