### ISSUE TITLE
Bigger reference plane wanted

### ISSUE THREAD

**Issue by joy13975** [joy13975/elfin-ui#15]
@parmef:

> Add option to make bigger reference plane in blender (right now is square with 16nm edge, it could be made 32, 64 or anything). This is good as reference during building.

**Comment by joy13975** [comment]
@parmef What about the following?
1) Press N to open right sidebar
2) Expand "Display" section
3) Change "Lines"

![](https://i.gyazo.com/1d73854a384daf3cef718ae27b10d41f.gif)

**Comment by parmef** [comment]
that's perfect.
